# Generated by Django 4.2.7 on 2024-05-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='Склад товару'),
        ),
    ]
