# Generated by Django 4.2.7 on 2024-05-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_goods_composition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='composition',
        ),
    ]
